### PR TITLE
Downcase users and fix reconciliation order

### PR DESCRIPTION
**Pull request by tanderegg**

### CODE REVIEW

**Comment by tanderegg** [comment]
@frank0631 Please review when you get a chance, thanks!

**Comment by frank0631** [comment]
I agree with the reordering of adding and purging. And I too find it annoying that active directory names are not consistent with case. Looks good

**Comment by frank0631** [comment]
does this close out issue #4 as well

**Comment by tanderegg** [comment]
No, but I might add that in this PR.

**Comment by tanderegg** [comment]
@frank0631 Nevermind, I'll add that fix later, it shouldn't be a problem in the near term anyways.

**Pull request merged**
