### PR TITLE
Citus

### PR DESCRIPTION
**Pull request by stirlingv**

### CODE REVIEW

**Comment by tanderegg** [comment]
@stirlingv Has this been tested in Staging?  Thanks!

**Comment by stirlingv** [comment]
@tanderegg Sure has, and you can verify that it's running by viewing the log - /var/log/psql-authnz.log.

**Comment by tanderegg** [comment]
@stirlingv Great, looks good!  This is a bit of a stretch goal, but it would be good to cause psql-authnz to output logs to journalctl, which is SystemD's central logging service.  I think you can just do this by commenting out the `PSQL_AUTHNZ_LOG_FILE` variable in the activate script, which causes it to log to stdout, and then this would get picked up by journalctl.  Then you could do "journalctl -u psql-authnz" and you should see those logs.  This is the "right" way to do it in SystemD land, and it has the added bonus of being picked up by Splunk automatically.

**Comment by stirlingv** [comment]
@tanderegg Looks like that worked in staging. I had to stop and start the service, but now when I check the journalctl it looks like the log output is there. 
```systemctl stop psql-authnz``` 
```systemctl start psql-authnz``` and 
```systemctl enable psql-authnz```

**Comment by tanderegg** [comment]
@stirlingv Yep, looks right to me, btw you can just do `systemctl restart psql-authnz`.  `enable` just ensures that the job starts on boot, as it should.  Thanks!

**Pull request merged**
